### ISSUE TITLE
chunkSize or chunkSizeBytes?

### ISSUE THREAD

**Issue by mfzl** [internalfx/rethinkdbfs-spec#8]
It's mentioned in the spec both ways. Personally I think `chunkSize` is better, since I don't ever see it being anything other than bytes.

**Comment by bchavez** [comment]
I like `chunkSize` too, but there was some wording IIRC in the original spec about some kind of confusion.

**Comment by internalfx** [comment]
It should certainly be consistent....

I went with `chunkSizeBytes` because it's consistent with GridFS (not like it matters).

But also it's clear what it is. It's clear to us because we remember, but it might not be clear to a newcomer if it was only `chunkSize`.

**Comment by bchavez** [comment]
or `chunkBytes`

**Comment by internalfx** [comment]
Like most things in programming.....

Saving key strokes does not save as much time as preventing confusion.

**Comment by internalfx** [comment]
@faxal Oh, and thank you for looking for errors in the spec.

I know there are still many, as it's very early in the project.

**Comment by internalfx** [comment]
We haven't even built a full implementation that I'm aware of.

**Comment by bchavez** [comment]
So far, operations that work in the C# driver:
- `Upload`: By bytes, streams, async
- `Download`: By bytes, streams, seek, async
- `List`: By prefix `/virtual_bucket`, async
- `Delete`:  etc., async

All passing unit tests are here:
https://github.com/bchavez/RethinkDb.Driver/tree/master/Source/RethinkDb.Driver.ReGrid.Tests

**Comment by mfzl** [comment]
It's no problem, I was giving a shot at a toy implementation myself.
